// M4 regression: batch mode — descriptors/QED/PAINS parity vs frozen refs,
// three-state sort (aria-sort), filter semantics (refs-derived expectations),
// error rows, CSV content, multi-record SDF input, cancel path, row-click
// reload, mode isolation, 3D + SDF provenance. Run: node m4_batch.test.js
// (needs the :8901 test server)
const { chromium } = require('/opt/homebrew/lib/node_modules/playwright');
const fs = require('fs');
const EXE = '/Users/rliu/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell';
const LBDD = JSON.parse(fs.readFileSync(__dirname + '/../fixtures/lbdd/batch_refs.json', 'utf8'));
// batch_refs.json values (generated by scripts/gen_batch_refs.py, RDKit
// 2026.03 like the vendored wasm) with discriminating corners: rhodanine
// (PAINS=1), metformin (QED<0.5), cholesterol (Lipinski fail via logP 7.39;
// QED<0.5), hexane (TPSA 0, no Murcko scaffold). One garbage line exercises
// the error row.
const PNAMES = ['caffeine', 'aspirin', 'ibuprofen', 'naproxen', 'paracetamol', 'rhodanine_nmethyl', 'metformin', 'cholesterol', 'hexane'];
const PINPUT = PNAMES.map(n => LBDD[n].smiles + ' ' + n).join('\n') + '\nnot_a_molecule broken-one';

const INPUT = [
  'CN1C=NC2=C1C(=O)N(C)C(=O)N2 caffeine',
  'CC(=O)Oc1ccccc1C(=O)O aspirin',
  'Cn1cnc2c1c(=O)n(C)c(=O)n2C theophylline',
].join('\n');

(async () => {
  const browser = await chromium.launch({ executablePath: EXE });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message.slice(0, 120)));

  let pass = 0, fail = 0;
  const check = (name, cond, detail = '') => {
    if (cond) { pass++; console.log(`  ✓ ${name}${detail ? ' — ' + detail : ''}`); }
    else { fail++; console.log(`  ✗ ${name}${detail ? ' — ' + detail : ''}`); }
  };

  await page.goto('http://localhost:8901/app/index.html', { waitUntil: 'load' });
  await page.waitForFunction(() => window.webmmReady === true, null, { timeout: 60000 });

  // 1. switch to batch tab, enter 3 molecules
  const tabs = await page.evaluate(() => {
    const tabs = [...document.querySelectorAll('.mode-tab')];
    const batch = tabs.find(t => /batch/i.test(t.textContent));
    if (batch) batch.click();
    return tabs.map(t => t.textContent.trim());
  });
  await page.evaluate(s => { document.getElementById('input').value = s; }, INPUT);
  await page.waitForTimeout(200);

  // 2. run batch (descriptors only)
  await page.evaluate(() => runBatch());
  await page.waitForFunction(() => {
    const rows = [...document.querySelectorAll('#batchRows tr, #batchTable tr')];
    return rows.length >= 3 && !batchRun;
  }, null, { timeout: 120000 });
  const rows1 = await page.evaluate(() => [...document.querySelectorAll('#batchRows tr, #batchTable tr')]
    .map(tr => tr.textContent.trim()).slice(0, 6));
  check('batch renders 3 rows', rows1.length >= 3, rows1.length + ' rows');
  check('rows carry names + descriptors', rows1.some(r => r.includes('caffeine')) && rows1.some(r => r.includes('aspirin')) && rows1.some(r => r.includes('MW') || r.includes('194') || r.includes('180')), rows1[1]?.slice(0, 50));

  // 3. CSV export
  const dl = await (async () => { const p = page.waitForEvent('download'); await page.evaluate(() => exportBatchCSV()); return p; })();
  await dl.saveAs('/tmp/batch_test.csv');
  const csv = fs.readFileSync('/tmp/batch_test.csv', 'utf8');
  check('CSV export has header + 3 rows', csv.split('\n').filter(l => l.trim()).length >= 4 && /name|smiles/i.test(csv.split('\n')[0]), csv.split('\n')[0].slice(0, 60));
  check('CSV includes caffeine row', /caffeine/.test(csv));

  // 4. 3D batch run (2 molecules: drop theophylline for speed) + SDF provenance
  await page.evaluate((s) => { document.getElementById('input').value = s.split('\n').slice(0, 2).join('\n'); }, INPUT);
  await page.evaluate(() => { document.getElementById('batch3d').checked = true; });
  await page.evaluate(() => runBatch());
  await page.waitForFunction(() => !batchRun, null, { timeout: 300000 });
  const sdfReady = await page.evaluate(() => batchResults.filter(r => r.sdf).length);
  check('3D batch produces SDFs', sdfReady >= 2, sdfReady + ' sdf rows');
  const dl2 = await (async () => { const p = page.waitForEvent('download'); await page.evaluate(() => exportBatchSDF()); return p; })();
  await dl2.saveAs('/tmp/batch_test.sdf');
  const sdf = fs.readFileSync('/tmp/batch_test.sdf', 'utf8');
  check('batch SDF carries provenance', sdf.includes('WEBMM_PROGRAM') && sdf.includes('WEBMM_ENGINE') && sdf.includes('$$$$'), 'WEBMM_PROGRAM/ENGINE present');

  // ================= refs-driven functional E2E =================
  const eqSet = (a, b) => a.length === b.length && [...a].sort().join('|') === [...b].sort().join('|');
  const f2 = (x) => x.toFixed(2);

  // 5. descriptor / QED / PAINS parity (9 refs-backed molecules + 1 error row)
  await page.evaluate(() => { document.getElementById('batch3d').checked = false; });
  await page.evaluate(s => { document.getElementById('input').value = s; }, PINPUT);
  await page.evaluate(() => runBatch());
  await page.waitForFunction(() => !batchRun, null, { timeout: 120000 });
  await page.waitForFunction(() => document.getElementById('batchRows').children.length === 10, null, { timeout: 30000 });
  const parity = await page.evaluate(() => {
    const out = {};
    for (const tr of document.querySelectorAll('#batchRows tr')) {
      const td = [...tr.querySelectorAll('td')].map(x => x.textContent.trim());
      if (td.length <= 3) { out[td[1]] = { error: td[2] || '' }; continue; }
      out[td[1]] = {
        MW: td[4], cLogP: td[5], TPSA: td[6], HBD: td[7], HBA: td[8], RotB: td[9],
        QED: td[10], painsText: td[11],
        badge: tr.children[11].querySelector('.result-badge') ? tr.children[11].querySelector('.result-badge').className : '',
      };
    }
    return out;
  });
  for (const n of PNAMES) {
    const ref = LBDD[n], g = parity[n] || {};
    const bad = [];
    if (g.error) bad.push('unexpected error row');
    if (g.MW !== f2(ref.MW)) bad.push(`MW ${g.MW}!=${f2(ref.MW)}`);
    if (g.cLogP !== f2(ref.cLogP)) bad.push(`cLogP ${g.cLogP}!=${f2(ref.cLogP)}`);
    if (g.TPSA !== f2(ref.TPSA)) bad.push(`TPSA ${g.TPSA}!=${f2(ref.TPSA)}`);
    if (g.HBD !== String(ref.HBD)) bad.push(`HBD ${g.HBD}!=${ref.HBD}`);
    if (g.HBA !== String(ref.HBA)) bad.push(`HBA ${g.HBA}!=${ref.HBA}`);
    if (g.RotB !== String(ref.RotB)) bad.push(`RotB ${g.RotB}!=${ref.RotB}`);
    if (g.QED !== f2(ref.qed_mean)) bad.push(`QED ${g.QED}!=${f2(ref.qed_mean)}`);
    if (g.painsText !== String(ref.pains)) bad.push(`PAINS ${g.painsText}!=${ref.pains}`);
    if (!g.badge || !g.badge.includes(ref.pains ? 'fail' : 'pass')) bad.push(`badge ${g.badge}`);
    check(`parity: ${n}`, bad.length === 0, bad.join('; ') || `${g.MW}/${g.cLogP}/${g.TPSA} QED ${g.QED} PAINS ${g.painsText}`);
  }
  check('error row rendered with message', parity['broken-one'] && !!parity['broken-one'].error, (parity['broken-one'] || {}).error);

  // 6. filters — expectations computed from the refs, not hard-coded
  const expect = {
    lipinski: PNAMES.filter(n => { const r = LBDD[n]; return r.MW <= 500 && r.cLogP <= 5 && r.HBD <= 5 && r.HBA <= 10; }),
    veber: PNAMES.filter(n => { const r = LBDD[n]; return r.TPSA <= 140 && r.RotB <= 10; }),
    qed: PNAMES.filter(n => LBDD[n].qed_mean >= 0.5),
    nopains: PNAMES.filter(n => LBDD[n].pains === 0),
  };
  for (const [f, exp] of Object.entries(expect)) {
    const vis = await page.evaluate((f) => {
      document.getElementById('batchFilter').value = f; applyBatchView();
      return [...document.querySelectorAll('#batchRows tr')].filter(tr => tr.style.display !== 'none').map(tr => tr.children[1].textContent.trim());
    }, f);
    check(`filter ${f} (${exp.length} expected)`, eqSet(vis, exp), eqSet(vis, exp) ? '' : 'page=' + JSON.stringify(vis));
  }
  const visAll = await page.evaluate(() => {
    document.getElementById('batchFilter').value = 'all'; applyBatchView();
    return [...document.querySelectorAll('#batchRows tr')].filter(tr => tr.style.display !== 'none').length;
  });
  check('filter all shows every row incl. the error row', visAll === 10, 'visible=' + visAll);
  const errHidden = await page.evaluate(() => {
    document.getElementById('batchFilter').value = 'lipinski'; applyBatchView();
    const tr = [...document.querySelectorAll('#batchRows tr')].find(t => t.children[1] && t.children[1].textContent.trim() === 'broken-one');
    const hidden = tr && tr.style.display === 'none';
    document.getElementById('batchFilter').value = 'all'; applyBatchView();
    return hidden;
  });
  check('error row hidden by non-all filters', errHidden);

  // 7. three-state sort by MW (NaN sinks; third click clears the key)
  const sortRes = await page.evaluate(() => {
    const vals = () => [...document.querySelectorAll('#batchRows tr')].map(tr => tr.children[4] ? parseFloat(tr.children[4].textContent) : NaN);
    const aria = () => document.querySelector('#batchTable th[data-key="MW"]').getAttribute('aria-sort');
    sortBatch('MW'); const asc = vals(), a1 = aria();
    sortBatch('MW'); const desc = vals(), a2 = aria();
    sortBatch('MW'); const a3 = aria();
    return { asc, desc, a1, a2, a3 };
  });
  const numAsc = sortRes.asc.filter(v => !isNaN(v));
  const numDesc = sortRes.desc.filter(v => !isNaN(v));
  check('sort MW ascending (hexane 86.18 first, NaN sinks)', numAsc[0] === 86.18 && numAsc.every((v, i, a) => i === 0 || a[i - 1] <= v) && sortRes.a1 === 'ascending', JSON.stringify(numAsc.slice(0, 3)));
  check('sort MW descending (cholesterol 386.66 first)', numDesc[0] === 386.66 && numDesc.every((v, i, a) => i === 0 || a[i - 1] >= v) && sortRes.a2 === 'descending', JSON.stringify(numDesc.slice(0, 3)));
  check('third click clears the sort key (aria-sort none)', sortRes.a3 === 'none');

  // 8. CSV content vs refs (QED mean 6dp, PAINS count, Murcko)
  const dl3 = await (async () => { const p = page.waitForEvent('download'); await page.evaluate(() => exportBatchCSV()); return p; })();
  await dl3.saveAs('/tmp/batch_refs.csv');
  const csvRows = fs.readFileSync('/tmp/batch_refs.csv', 'utf8').trim().split('\n').map(l => l.split(','));
  const csvHead = csvRows[0];
  const col = (name) => csvHead.indexOf(name);
  const csvByName = Object.fromEntries(csvRows.slice(1).map(r => [r[0], r]));
  let csvBad = [];
  for (const n of PNAMES) {
    const r = csvByName[n], ref = LBDD[n];
    if (!r) { csvBad.push(n + ' missing'); continue; }
    if (r[col('QED mean')] !== ref.qed_mean.toFixed(6)) csvBad.push(`${n} QED ${r[col('QED mean')]}!=${ref.qed_mean.toFixed(6)}`);
    if (r[col('PAINS')] !== String(ref.pains)) csvBad.push(`${n} PAINS ${r[col('PAINS')]}!=${ref.pains}`);
    if (r[col('Murcko')] !== ref.murcko) csvBad.push(`${n} Murcko ${r[col('Murcko')]}!=${ref.murcko}`);
  }
  check('CSV QED(6dp)/PAINS/Murcko == refs for all 9', csvBad.length === 0, csvBad.slice(0, 3).join('; ') || 'exact');
  check('CSV carries an ERROR row for the garbage input', /broken-one,not_a_molecule,ERROR/.test(fs.readFileSync('/tmp/batch_refs.csv', 'utf8')));

  // 9. row click loads into the single view (canonical SMILES match)
  await page.evaluate(() => {
    const tr = [...document.querySelectorAll('#batchRows tr')].find(t => t.children[1].textContent.trim() === 'naproxen');
    loadBatchRow(+tr.dataset.idx);
  });
  await page.waitForTimeout(600);
  const rowLoad = await page.evaluate(() => ({
    single: document.getElementById('tabSingle').classList.contains('active'),
    output: document.getElementById('output').style.display,
    smiles: document.getElementById('smiles').textContent,
  }));
  check('row click loads single view with the right molecule', rowLoad.single && rowLoad.output === 'block' && rowLoad.smiles === LBDD.naproxen.smiles, rowLoad.smiles);

  // 10. multi-record SDF input parses by record (names from title lines)
  const sdfRows = await page.evaluate(async ([s1, s2]) => {
    switchMode('batch');
    const mk = (smi, name) => {
      const m = rdkitModule.get_mol(smi);
      const L = m.get_molblock().split('\n');
      L[0] = name;
      m.delete();
      return L.join('\n');
    };
    document.getElementById('input').value = mk(s1, 'caff-sdf') + '\n$$$$\n' + mk(s2, 'asp-sdf') + '\n$$$$';
    runBatch();
    await new Promise(r => { const t = setInterval(() => { if (!batchRun) { clearInterval(t); r(); } }, 200); });
    return [...document.querySelectorAll('#batchRows tr')].map(tr => ({ name: tr.children[1].textContent.trim(), mw: tr.children[4].textContent.trim() }));
  }, [LBDD.caffeine.smiles, LBDD.aspirin.smiles]);
  check('SDF input yields one row per record with title names',
    sdfRows.length === 2 && eqSet(sdfRows.map(r => r.name), ['caff-sdf', 'asp-sdf']) && sdfRows.every(r => /^\d+\.\d+$/.test(r.mw)),
    JSON.stringify(sdfRows));

  // 11. cancel path (3D batch cancelled immediately after kick-off: the
  // descriptor phase is synchronous, so the worker farm is always mid-flight
  // here — no timing window)
  // double the molecule list: the 10-line run can complete inside the
  // 100 ms timer on a warm page (synchronous descriptor phase ~100 ms —
  // knife-edge, flipped by load/wasm import timing); ~19 lines of real
  // conformer work make mid-flight unambiguous
  const PINPUT2 = PINPUT + '\n' + PINPUT;
  await page.evaluate((s) => {
    document.getElementById('batch3d').checked = true;
    document.getElementById('input').value = s;
    runBatch();
  }, PINPUT2);
  await page.waitForTimeout(100);
  await page.evaluate(() => cancelBatch());
  const cc = await page.evaluate(() => ({
    status: document.getElementById('batchStatus').textContent,
    running: !!batchRun,
    btnRun: document.getElementById('btnBatchRun').style.display,
    btnCancel: document.getElementById('btnBatchCancel').style.display,
  }));
  check('cancel stops the run and restores the buttons', cc.status === 'Cancelled' && !cc.running && cc.btnRun !== 'none' && cc.btnCancel === 'none', JSON.stringify(cc));
  await page.evaluate(() => { document.getElementById('batch3d').checked = false; });
  await page.evaluate((s) => { document.getElementById('input').value = s; }, PINPUT);

  // 12. mode isolation: batch input + panel leave and return intact
  const iso = await page.evaluate(() => {
    const before = { panel: document.getElementById('batchPanel').style.display };
    switchMode('single');
    const inSingle = { panel: document.getElementById('batchPanel').style.display, input: document.getElementById('input').value };
    switchMode('batch');
    const back = { panel: document.getElementById('batchPanel').style.display, input: document.getElementById('input').value };
    return { before, inSingle, back };
  });
  check('batch input + panel hidden in single, restored on return',
    iso.before.panel === 'block' && iso.inSingle.panel === 'none' && iso.back.panel === 'block' && iso.back.input === PINPUT && iso.inSingle.input !== PINPUT);

  // 13. zero page errors
  check('zero page errors', errors.length === 0, errors.slice(0, 2).join(' | '));

  console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
  await browser.close();
  process.exit(fail ? 1 : 0);
})();
