#!/usr/bin/env python3
"""Generate app/demo_library.js — the bundled demo library for the Workbench
Search tab.

Sources (zero hand-written SMILES):
  - test_molecules/*.sdf — the repo's engine-validated molecule set
    (name = SDF title or filename; family = filename prefix)
  - the drug-like named subset of tests/fixtures/lbdd/refs.json

Output: window.DEMO_LIBRARY = [{name, smiles, family}, ...] (canonical SMILES).

Usage: python3 scripts/gen_demo_library.py
"""
import json
import sys
from pathlib import Path

from rdkit import Chem

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "app" / "demo_library.js"
REFS = REPO / "tests" / "fixtures" / "lbdd" / "refs.json"

# Named, drug-like entries pulled from the LBDD reference set (curated subset:
# recognizable molecules that make similarity demos intuitive).
REF_NAMES = [
    "aspirin", "ibuprofen", "paracetamol", "caffeine", "theophylline",
    "nicotine", "diclofenac", "warfarin", "propranolol", "metoprolol",
    "naproxen", "lidocaine", "benzocaine", "salicylic_acid", "cholesterol",
    "naphthalene", "anthracene", "glucose_alpha",
]

MAX_LIBRARY = 2000


def main() -> int:
    entries = []
    seen = set()

    for sdf in sorted((REPO / "test_molecules").glob("*.sdf")):
        supp = Chem.SDMolSupplier(str(sdf), removeHs=True, sanitize=True)
        mol = next(iter(supp), None)
        if mol is None:
            continue
        title = (sdf.stem).replace("_", " ")
        smi = Chem.MolToSmiles(mol)
        if not smi or smi in seen:
            continue
        seen.add(smi)
        family = sdf.stem.rsplit("_", 1)[0].replace("_", " ")
        if family == "test":
            family = "Amines"   # test.sdf holds a secondary amine; name the family honestly
        entries.append({"name": title, "smiles": smi, "family": family})

    n_test = len(entries)
    refs = json.loads(REFS.read_text())
    for name in REF_NAMES:
        rec = refs.get(name)
        if not rec:
            continue
        smi = Chem.MolToSmiles(Chem.MolFromSmiles(rec["smiles"]))
        if smi in seen:
            continue
        seen.add(smi)
        entries.append({"name": name.replace("_", " "), "smiles": smi, "family": "named drugs"})

    if len(entries) > MAX_LIBRARY:
        entries = entries[:MAX_LIBRARY]
    assert len(entries) >= 40, f"demo library suspiciously small: {len(entries)}"

    provenance = {
        "test_molecules": n_test,
        "named_drug_like": len(entries) - n_test,
        "total": len(entries),
    }
    js = (
        "/* Generated by scripts/gen_demo_library.py — do not edit by hand.\n"
        " * Provenance: "
        + json.dumps(provenance)
        + "\n"
        " */\n"
        "window.DEMO_LIBRARY = "
        + json.dumps(entries, separators=(",", ":"))
        + ";\n"
    )
    OUT.write_text(js)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes) {provenance}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
